# Generated by Django 4.2.1 on 2023-10-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_auctionlist_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
